version: '3.2'
services:
  admin:
    image: opentutor/opentutor-admin:2.6.4-alpha.2
    environment:
      - NODE_ENV
      - GRAPHQL_ENDPOINT=http://graphql:3001/graphql
    depends_on:
      - graphql
  classifier:
    image: opentutor/opentutor-classifier-api:2.6.0-alpha.14
    depends_on:
      - redis
    links:
      - redis
    ports:
      - 5000:5000
    environment:
      - GRAPHQL_ENDPOINT=http://graphql:3001/graphql
      - MODEL_ROOT
      - MODEL_DEPLOYED_ROOT
      - SHARED_ROOT
      - STATUS_URL_FORCE_HTTPS
    volumes:
      - type: bind
        source: ./build/run/.env
        target: /app/.env
      - type: bind
        source: ./models
        target: /app/models
        read_only: true
      - type: bind
        source: ./shared
        target: /app/shared
        read_only: true
      - type: bind
        source: ./models_deployed
        target: /app/models_deployed
        read_only: true
  dialog:
    image: opentutor/opentutor-dialog:2.6.1
    ports:
      - 3000:3000
    environment:
      - NODE_ENV
      - CLASSIFIER_ENDPOINT=http://classifier:5000/classifier/evaluate/
      - GRAPHQL_ENDPOINT=http://graphql:3001/graphql
      - LOG_LEVEL_DIALOG
    volumes:
      - type: bind
        source: ./build/run/.env
        target: /app/.env
    depends_on:
      - classifier
      - graphql
    links:
      - classifier
      - graphql
  graphql:
    image: opentutor/opentutor-graphql:2.6.0-alpha.4
    ports:
      - 3001:3001
    environment:
      - NODE_ENV
      - MONGO_URI
    volumes:
      - type: bind
        source: ./build/run/.env
        target: /app/.env
  home:
    image: opentutor/opentutor-home:2.6.0-alpha.1
    environment:
      - GRAPHQL_ENDPOINT=http://graphql:3001/graphql
    depends_on:
      - graphql
      - admin
      - tutor
    volumes:
      - type: bind
        source: ./build/run/.env
        target: /app/.env
  nginx:
    image: nginx:1-alpine
    ports:
      - 80:80
    depends_on:
      - admin
      - classifier
      - dialog
      - graphql
      - home
      - status
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: ./nginx/conf.d
        target: /etc/nginx/conf.d
  redis:
    image: 'redis:6-alpine'
    ports:
      - '6379:6379'
  status:
    image: opentutor/opentutor-status:2.6.0-alpha.1
    depends_on:
      - admin
      - classifier
      - dialog
      - graphql
      - home
      - tutor
    links:
      - admin
      - classifier
      - dialog
      - graphql
      - home
      - tutor
  training:
    image: opentutor/opentutor-classifier:2.6.0-alpha.14
    depends_on:
      - graphql
      - redis
    entrypoint: /app/training_worker.sh
    environment:
      - GRAPHQL_ENDPOINT=http://graphql:3001/graphql
      - LOG_LEVEL_CLASSIFIER=DEBUG
      - MODEL_ROOT
      - MODEL_DEPLOYED_ROOT
      - SHARED_ROOT
    links:
      - graphql
      - redis
    volumes:
      - type: bind
        source: ./build/run/.env
        target: /app/.env
      - type: bind
        source: ./archive
        target: /app/archive
      - type: bind
        source: ./models
        target: /app/models
      - type: bind
        source: ./models_deployed
        target: /app/models_deployed
        read_only: true
      - type: bind
        source: ./shared
        target: /app/shared
        read_only: true
  tutor:
    image: opentutor/opentutor-web-client:2.6.4-alpha.1
